In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
tf.__version__

'2.4.1'

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
dupes = df.duplicated()
print('No of duplicates:', dupes.sum())
df[dupes]

No of duplicates: 0


Empty DataFrame
Columns: [RowNumber, CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []

In [7]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [8]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [11]:
ct = ColumnTransformer(transformers=[('encoders', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33, random_state=42)

In [13]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(6700, 12)
(3300, 12)
(6700,)
(3300,)


In [14]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
ann = tf.keras.models.Sequential()

In [16]:
ann.add(tf.keras.layers.Dense(units = 20, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 20, activation = 'relu'))

ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [17]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs= 100)

Epoch 1/100
210/210 [==============================] - 1s 1ms/step - loss: 0.5953 - accuracy: 0.6788
Epoch 2/100
210/210 [==============================] - 0s 1ms/step - loss: 0.4321 - accuracy: 0.8190
Epoch 3/100
210/210 [==============================] - 0s 1ms/step - loss: 0.4155 - accuracy: 0.8218
Epoch 4/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3972 - accuracy: 0.8346
Epoch 5/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3761 - accuracy: 0.8476
Epoch 6/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3736 - accuracy: 0.8492
Epoch 7/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3551 - accuracy: 0.8549
Epoch 8/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.8619
Epoch 9/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3571 - accuracy: 0.8533
Epoch 10/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3421 - accura

210/210 [==============================] - 0s 1ms/step - loss: 0.2942 - accuracy: 0.8762
Epoch 82/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3043 - accuracy: 0.8676
Epoch 83/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3058 - accuracy: 0.8726
Epoch 84/100
210/210 [==============================] - 0s 1ms/step - loss: 0.2980 - accuracy: 0.8749
Epoch 85/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3010 - accuracy: 0.8774
Epoch 86/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8717
Epoch 87/100
210/210 [==============================] - 0s 1ms/step - loss: 0.2918 - accuracy: 0.8773
Epoch 88/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3016 - accuracy: 0.8729
Epoch 89/100
210/210 [==============================] - 0s 1ms/step - loss: 0.3071 - accuracy: 0.8753
Epoch 90/100
210/210 [==============================] - 0s 1ms/step - loss: 0.2954 - accuracy: 

In [19]:
#Predict on the train set
y_train_pred = ann.predict(X_train)
#Predict on the test set
y_test_pred = ann.predict(X_test)
y_test_pred = (y_test_pred > 0.5)

In [20]:
np.concatenate((y_test_pred.reshape(len(y_test_pred),1), y_test.reshape(len(y_test),1)),1)

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [1, 1]], dtype=int64)

In [21]:
print(confusion_matrix(y_test, y_test_pred))

[[2490  167]
 [ 303  340]]


In [22]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.89      0.94      0.91      2657
           1       0.67      0.53      0.59       643

    accuracy                           0.86      3300
   macro avg       0.78      0.73      0.75      3300
weighted avg       0.85      0.86      0.85      3300



In [23]:
#print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))> 0.5)